apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/jboss-openshift/openshift-quickstarts
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: "2022-06-06T10:09:37Z"
  labels:
    app: openshift-quickstarts
    app.kubernetes.io/component: openshift-quickstarts
    app.kubernetes.io/instance: openshift-quickstarts
    app.kubernetes.io/name: openshift-quickstarts
    app.kubernetes.io/part-of: openshift-quickstarts-app
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-11-ubi8
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:app.openshift.io/vcs-ref: {}
          f:app.openshift.io/vcs-uri: {}
          f:openshift.io/generated-by: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/part-of: {}
          f:app.openshift.io/runtime: {}
          f:app.openshift.io/runtime-version: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":8080,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
          k:{"port":8443,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
          k:{"port":8778,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
          f:deploymentconfig: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: Mozilla
    operation: Update
    time: "2022-06-06T10:09:37Z"
  name: openshift-quickstarts
  namespace: lantik-java-sample
  resourceVersion: "758672485"
  uid: f0a95d87-e4dd-4233-a0e0-80677aa25a23
spec:
  clusterIP: 10.222.228.54
  clusterIPs:
  - 10.222.228.54
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: 8778-tcp
    port: 8778
    protocol: TCP
    targetPort: 8778
  selector:
    app: openshift-quickstarts
    deploymentconfig: openshift-quickstarts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
